### PR TITLE
Refactor of existing code

### LINKED ISSUE #17: Seperate component styling

### LINKED ISSUE #18: [Refactor of code] Splitting up styled components

### PR DESCRIPTION
**Pull request by jacobatan**
- Seperated styles and components and put them in folders - follows best practices
- Added global styles to styles folder
- Added Nav and Footer to events page
- Before merging, should we make the styled components .ts or .tsx?

### CODE REVIEW

**Comment by KikoIlievski** [comment]
-  **Suggestion:** For separated styles, should the `SponsorsPage` also have its own folder with its own style file as well?
- Global styles look good
- Nav and footer added to the events page is a much nicer feature than previous
- As for the file extensions, I think it only needs to be `.tsx` if we plan to render components. We probably shouldn't be rendering react components in the style files, so I do think `.ts` is the correct choice.

**Review by KikoIlievski — COMMENTED** [review]
- **Suggestion**: For separated styles, should the SponsorsPage also have its own folder with its own style file as well?
**Question:** I noticed removing the `import react` from some component files. We could remove it from `FullScreenMenu.tsx`, `NavBar.tsx`, `SponsorsPage.tsx`, `MainRouter.tsx` and `index.tsx` for consistency. Though I'm not sure why this works in all honesty, or if we should be doing it.
- Global styles look good
- Nav and footer added to the events page is a much nicer feature than previous
- As for the file extensions, I think it only needs to be `.tsx` if we plan to render components. We probably shouldn't be rendering react components in the style files, so I do think `.ts` is the correct choice.

**Comment by jacobatan** [comment]
- I must've missed the SponsorsPage! I've added it now.
- I have also removed `import react` from the other files. It isn't required to import react as of React 17. This is because of the [`JSX Transform`](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html).
- I like keeping the styled components as .ts as well!

**Comment by KikoIlievski** [comment]
Everything looks good!

**Pull request merged**
